name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system packages (Tesseract for OCR)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Upgrade pip and install deps (if file exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests (or skip if none)
        run: |
          if [ -d tests ]; then
            python -m unittest discover -s tests
          else
            echo "No tests directory found, skipping."
          fi
